### ISSUE TITLE
Strong Customer Authentication (SCA) warning from Stripe

### ISSUE THREAD

**Issue by phingoc1** [Henshall/stripe_wrapper#2]
Hi, 

Got an email from Stripe saying my payment integration is not SCA compatible. I am using this wrapper out of the box with no changes except for API keys ofc. 

How can this wrapper be updated to meet SCA requirements?

**Comment by Henshall** [comment]
Hmmm are you charging European based cards?  Can you show the email you received and what it said (make sure to leave out any personal or sensitive information)? What is the front end HTML you are using on your site to collect the card information?

If you are charging European cards you may need to a "3d secure flow" to collect and charge credit cards based upon what I have been reading in the stripe documentation. Let me know and we can solve this. Thanks!

**Comment by phingoc1** [comment]
We are charging Norwegian credit cards. 
I am using your front end 2 example from readme.md. 

Do you know if 3d secure flow is something we must implement in code, or some kind of setting/activation in the Stripe portal? 


![Screenshot 2020-11-08 at 18 06 06](https://user-images.githubusercontent.com/61778162/98471530-409e1600-21ed-11eb-86d7-dbfe20af5583.png)

**Comment by phingoc1** [comment]
I did some more digging, and found out that this is related to Two Factor Authentication. All EU based payments where you enter your credit card information and purchase amount is over 30 Euros, secondary authentication must be used. This is according to the new PSD-2 rules in EU.
